apiVersion: v1
kind: Service
metadata:
  name: ad-generator-service
  namespace: ad-generator
  labels:
    app: ad-generator
spec:
  type: LoadBalancer
  selector:
    app: ad-generator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: None
